apiVersion: v1
kind: Service
metadata:
  name: call-agent-backend
spec:
  selector:
    app: call-agent-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
